#########################################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.                    #
# SPDX-License-Identifier: MIT-0                                                        #
#                                                                                       #
# Permission is hereby granted, free of charge, to any person obtaining a copy of this  #
# software and associated documentation files (the "Software"), to deal in the Software #
# without restriction, including without limitation the rights to use, copy, modify,    #
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to    #
# permit persons to whom the Software is furnished to do so.                            #
#                                                                                       #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,   #
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A         #
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT    #
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION     #
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE        #
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                #
#########################################################################################

AWSTemplateFormatVersion: 2010-09-09
Description: "AWS CloudFormation template for creating MGN Required Roles"
Resources:

  rMGNReplicationServerRole:
    Metadata:
      cfn_nag:
          rules_to_suppress:
          - id: W28
            reason: "Explicit resource name required for DRS initialization IAM roles"
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSApplicationMigrationReplicationServerRole
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSApplicationMigrationReplicationServerPolicy
  
  rMGNReplicationServerInstanceProfileReplication:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref rMGNReplicationServerRole

  rMGNConversionServerRole:
    Metadata:
      cfn_nag:
          rules_to_suppress:
          - id: W28
            reason: "Explicit resource name required for DRS initialization IAM roles"
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSApplicationMigrationConversionServerRole
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSApplicationMigrationConversionServerPolicy

  rMGNReplicationServerInstanceProfileConversion:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref rMGNConversionServerRole

  rMGNMigrationHubRole:
    Metadata:
      cfn_nag:
          rules_to_suppress:
          - id: W28
            reason: "Explicit resource name required for DRS initialization IAM roles"
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSApplicationMigrationMGHRole
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: mgn.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSApplicationMigrationMGHAccess

  rMGNLaunchInstanceWithDrsRole:
    Metadata:
      cfn_nag:
          rules_to_suppress:
          - id: W28
            reason: "Explicit resource name required for DRS initialization IAM roles"
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSApplicationMigrationLaunchInstanceWithDrsRole
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSElasticDisasterRecoveryEc2InstancePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  rMGNLaunchInstanceWithSsmRole:
    Metadata:
      cfn_nag:
          rules_to_suppress:
          - id: W28
            reason: "Explicit resource name required for DRS initialization IAM roles"
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSApplicationMigrationLaunchInstanceWithSsmRole
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  rMGNAgentRole:
    Metadata:
      cfn_nag:
          rules_to_suppress:
          - id: W28
            reason: "Explicit resource name required for DRS initialization IAM roles"
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSApplicationMigrationAgentRole
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: mgn.amazonaws.com
          Action: 
            - sts:AssumeRole
            - sts:SetSourceIdentity
          Condition:
            StringLike:
              sts:SourceIdentity: "s-*"
              aws:SourceAccount: !Sub ${AWS::AccountId}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSApplicationMigrationAgentPolicy_v2