#########################################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.                    #
# SPDX-License-Identifier: MIT-0                                                        #
#                                                                                       #
# Permission is hereby granted, free of charge, to any person obtaining a copy of this  #
# software and associated documentation files (the "Software"), to deal in the Software #
# without restriction, including without limitation the rights to use, copy, modify,    #
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to    #
# permit persons to whom the Software is furnished to do so.                            #
#                                                                                       #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,   #
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A         #
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT    #
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION     #
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE        #
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                #
#########################################################################################

AWSTemplateFormatVersion: 2010-09-09
Description: This template initializes DRS and configures replication settings

Parameters: 
  pReplicationSubnetId:
    Description: Subnet Id for Replication Server
    Type: AWS::EC2::Subnet::Id
  pReplicationInstanceType:
    Description: Replication Server Instance Type
    Default: "t3.small"
    Type: String
  pReplicationSecurityGroupIds:
    Description: Security Group Ids for Replication Servers
    Type: List<AWS::EC2::SecurityGroup::Id>
  pKMSKeyArn:
    Description: ARN of KMS Key for EBS Encryption (Leave blank for Amazon Managed KMS)
    Type: String
    Default: ""
  pReplicationServerTags:
    Description: Tags for replication servers (Please specify in KEY:VALUE format. Multiple entries can be comma separated)
    Type: CommaDelimitedList
    Default: "Division:TEST,Environment:Dev,Application:testapp,DataClassification:Proprietary,CostCenter:999999999,Consumer:tcconlin@amazon.com"
  pCreateReplicationSecurityGroup:
    Description: Create default replication security group
    Type: String
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  pReplicationServerPublicIp:
    Description: Use Public IP for Replication server control plane traffic
    Type: String
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  pReplicationServerDataRouting:
    Description: Replication Server data plane traffic connectivity
    Type: String
    Default: PRIVATE_IP
    AllowedValues:
      - PUBLIC_IP
      - PRIVATE_IP
  pReplicationDataThrottling:
    Description: Throttle Replication traffic. (Set to 0 to use all available bandwidth on source server or else specify a value to limit bandwidth usage)
    Type: Number
    Default: 0
  pReplicationStagingDiskType:
    Description: Replication Server staging disk type
    Type: String
    Default: 'GP3'
    AllowedValues:
      - 'GP3'
      - 'GP2'
      - 'ST1'
  pUseDedicatedReplicationServer:
    Description: Use dedicated replication server for each source machine
    Type: String
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  pPitPolicyMinute:
    Description: The by Minute Point in time (PIT) policy to manage snapshots taken during replication.
    Type: CommaDelimitedList
    Default: 'enabled:True,interval:10,retentionDuration:60,ruleID:1,units:MINUTE'
  pPitPolicyHour:
    Description: The Hourly Point in time (PIT) policy to manage snapshots taken during replication.
    Type: CommaDelimitedList
    Default: 'enabled:True,interval:1,retentionDuration:24,ruleID:2,units:HOUR'
  pPitPolicyDay:
    Description: The Daily Point in time (PIT) policy to manage snapshots taken during replication.
    Type: CommaDelimitedList
    Default: 'enabled:True,interval:1,retentionDuration:10,ruleID:3,units:DAY'

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Replication Server Settings"
        Parameters: 
          - pReplicationInstanceType
          - pReplicationStagingDiskType
          - pUseDedicatedReplicationServer
          - pKMSKeyArn
          - pReplicationServerTags
      - 
        Label: 
          default: "Replication Network Setting"
        Parameters: 
          - pReplicationSubnetId
          - pReplicationSecurityGroupIds
          - pReplicationServerPublicIp
          - pReplicationServerDataRouting
          - pReplicationDataThrottling
          - pCreateReplicationSecurityGroup

    ParameterLabels: 
      pReplicationSubnetId: 
        default: "Replication Server Subnet"
      pReplicationSecurityGroupIds:
        default: "Replication Server Security Groups"
      pReplicationInstanceType:
        default: "Replication Server Instance Type"
      pKMSKeyArn:
        default: "KMS Key ARN for EBS encryption"
      pReplicationServerTags:
        default: "Tags to be applied to replication server"
      pCreateReplicationSecurityGroup:
        default: "Create new replication security group"
      pReplicationServerPublicIp:
        default: "Use Public IP for Replication server control plane traffic"
      pReplicationServerDataRouting:
        default: "Replication Server data plane traffic connectivity"
      pReplicationDataThrottling:
        default: "Replication Bandwidth limit in MB"
      pReplicationStagingDiskType:
        default: "Replication Server staging disk type"
      pUseDedicatedReplicationServer:
        default: "Use dedicated replication server for each source machine"

Conditions:
  cDefaultKMS:
    !Equals [!Ref pKMSKeyArn, ""]

Resources:

  rDRSInitializerLambdaIamRole:
    Metadata:
      cfn_nag:
          rules_to_suppress:
          - id: W11
            reason: "Resource Wildcard required for dynamic resource creation"
      checkov:
        skip:
          - id: CKV_AWS_111
            comment: "Resource Wildcard required for dynamic resource creation"
          - id: CKV_AWS_107
            comment: "Lambda not logging sensitive data"
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              aws:SourceArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:DRSInitializer
      Path: "/"
      Policies:
        - PolicyName: DRSInitializerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: LambdaLogging
              Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
            - Sid: EC2Read
              Effect: Allow
              Action:
              - ec2:Describe*
              - ec2:Get*
              Resource: "*"
            - Sid: EC2Access
              Effect: Allow
              Action:
              - ec2:CreateSecurityGroup
              - ec2:CreateTags
              Resource: "*"
            - Sid: AllowIAMCreationforServiceInitialization
              Effect: Allow
              Action:
              - iam:CreateInstanceProfile
              - iam:CreateServiceLinkedRole
              - iam:DeleteServiceLinkedRole
              - iam:AddRoleToInstanceProfile
              - iam:CreateRole
              - iam:DeleteRole
              Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/AWSElasticDisasterRecovery*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:instance-profile/AWSElasticDisasterRecovery*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/drs.amazonaws.com/AWSServiceRoleForElasticDisasterRecovery"
            - Sid: IAMGetInstanceProfile
              Effect: Allow
              Action: iam:GetInstanceProfile
              Resource: "*"
            - Sid: DRSAccess
              Effect: Allow
              Action:
              - drs:InitializeService
              - drs:CreateReplicationConfigurationTemplate
              - drs:UpdateReplicationConfigurationTemplate
              - drs:DeleteReplicationConfigurationTemplate
              Resource: "*"
            - Sid: KMSAccess
              Effect: Allow
              Action:
              - kms:CreateGrant
              - kms:DescribeKey
              Resource:
              - !If [ cDefaultKMS, !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/PLACEHOLDER_KEY_ID", !Ref pKMSKeyArn ]
            - Sid: PassRoleDRS
              Effect: Allow
              Action: iam:PassRole
              Resource: 
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/AWSElasticDisasterRecovery*"
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/AWSElasticDisasterRecovery*"

  rDRSInitializerLambdaFunction:
    Metadata:
      cfn_nag:
          rules_to_suppress:
          - id: W92
            reason: "Function will invoke individually for service initalization"
          - id: W89
            reason: "Function does not access VPC attached resources and should not have VPC dependency"
      checkov:
        skip:
          - id: CKV_AWS_115
            comment: Function will be invoked once per Service Catalog Product deployment
          - id: CKV_AWS_116
            comment: CloudFormation custom resource Lambda - use CloudWatch logs for troubleshooting
          - id: CKV_AWS_117
            comment: Not a valid use case for Lambda function to be deployed inside a VPC
    Type: AWS::Lambda::Function
    Properties:
      Description: Performs DRS initalization and configures replication setting
      FunctionName: DRSInitializer
      Handler: index.lambda_handler
      MemorySize: 128
      Role: !GetAtt rDRSInitializerLambdaIamRole.Arn
      Runtime: python3.8
      Timeout: 60
      Code:
        ZipFile: |
          import boto3
          import botocore
          import json
          import cfnresponse

          drs = boto3.client('drs')
          kms = boto3.client('kms')

          def convert_list_to_dict(list):
            list_d = {}
            for item in list:
              k,v = item.split(":", 1)
              list_d[k] = v
            return list_d

          def convert_pit_types(pitPolicy):
            if pitPolicy['enabled'] == 'True':
                pitPolicy['enabled'] = True
            else:
                pitPolicy['enabled'] = False
            
            pitPolicy['interval'] = int(pitPolicy['interval'])
            pitPolicy['retentionDuration'] = int(pitPolicy['retentionDuration'])
            pitPolicy['ruleID'] = int(pitPolicy['ruleID'])
            
            return pitPolicy

          def create_kms_grant(kmsKey, grantee):
            response = kms.create_grant(
              KeyId=kmsKey,
              GranteePrincipal=grantee,
              RetiringPrincipal=grantee,
              Operations=['Decrypt','Encrypt','GenerateDataKey','GenerateDataKeyWithoutPlaintext','CreateGrant','DescribeKey'],
              Name='ElasticDisasterRecovery'
          )

          def lambda_handler(event, context):
            print(json.dumps(event))
            request_params = event['ResourceProperties']
            request_type = event['RequestType']
            if request_params['KMSKeyArn'] != '':
              kmsKeyArn = request_params['KMSKeyArn']
            else:
              kmsKeyArn = None
            instanceType = request_params['ReplicationInstanceType']
            securityGroupIds = request_params['ReplicationSecurityGroupIds']
            subnet = request_params['StagingSubnetId']
            dataRouting = request_params['ReplicationDataRouting']
            diskType = request_params['StagingDiskType']
            bandwitdh = request_params['ReplicationBandwidthInMB']
            dedicatedReplicationServer = False
            createSecurityGroup = False
            publicIp = False

            if (request_params['CreateReplicationSecurityGroup']) == 'Yes':
              createSecurityGroup = True
            if (request_params['CreatePublicIp']) == 'Yes':
              publicIp = True
            if (request_params['UseDedicatedReplicationServer']) == 'Yes':
              dedicatedReplicationServer = True

            tags = request_params['Tags']
            stagingTags = convert_list_to_dict(tags)

            pitMinute = request_params['PitPolicyMinute']
            pitPolMinute = convert_list_to_dict(pitMinute)

            pitHour = request_params['PitPolicyHour']
            pitPolHour = convert_list_to_dict(pitHour)

            pitDay = request_params['PitPolicyDay']
            pitPolDay = convert_list_to_dict(pitDay)

            rep_config_req_params = {}
            rep_config_req_params['associateDefaultSecurityGroup']=createSecurityGroup
            rep_config_req_params['bandwidthThrottling']=int(bandwitdh)
            rep_config_req_params['createPublicIP']=publicIp
            rep_config_req_params['dataPlaneRouting']=dataRouting
            rep_config_req_params['defaultLargeStagingDiskType']=diskType
            if kmsKeyArn is not None:
              rep_config_req_params['ebsEncryption']='CUSTOM'
              rep_config_req_params['ebsEncryptionKeyArn']=kmsKeyArn
            else:
              rep_config_req_params['ebsEncryption']='DEFAULT'
            rep_config_req_params['replicationServerInstanceType']=instanceType
            rep_config_req_params['replicationServersSecurityGroupsIDs']=securityGroupIds
            rep_config_req_params['stagingAreaSubnetId']=subnet
            rep_config_req_params['stagingAreaTags']=stagingTags
            rep_config_req_params['useDedicatedReplicationServer']=dedicatedReplicationServer
            
            
            # Convert pitPolicy types from strings to proper types
            pitPolMinute = convert_pit_types(pitPolMinute)
            pitPolHour = convert_pit_types(pitPolHour)
            pitPolDay = convert_pit_types(pitPolDay)

            rep_config_req_params['pitPolicy']=[pitPolMinute, pitPolHour, pitPolDay]

            rId = None
            response = None
            aws_account_id = context.invoked_function_arn.split(":")[4]
            drs_service_role_arn = f"arn:aws:iam::{aws_account_id}:role/aws-service-role/drs.amazonaws.com/AWSServiceRoleForElasticDisasterRecovery"
            if request_type == "Create" or request_type == "Update":
              print(f'Processing a {request_type} request')
              try:
                if request_type == "Create":
                  print("Initializing DRS")
                  drs.initialize_service()
                  print("DRS initalized, setting up replication config")
                  response = drs.create_replication_configuration_template(**rep_config_req_params)
                  print(f'Response from creating resplication configuration: {response}')
                  if kmsKeyArn is not None:
                    print('Creating KMS Grant')
                    create_kms_grant(kmsKeyArn, drs_service_role_arn)
                    print('KMS Grant Created')
                  rId = response['replicationConfigurationTemplateID']
                  print(f'Replication Configuration Template ID: {rId}')
                  print("Completed Init of DRS")
                else:
                  print("Updating replication config")
                  rId = event['PhysicalResourceId']
                  rep_config_req_params['replicationConfigurationTemplateID']=rId
                  response = drs.update_replication_configuration_template(**rep_config_req_params)
                  rId = response['replicationConfigurationTemplateID']
                  oldKmsKeyArn = event['OldResourceProperties']['KMSKeyArn']
                  if kmsKeyArn is not None and oldKmsKeyArn != kmsKeyArn:
                    create_kms_grant(kmsKeyArn, drs_service_role_arn)
              except Exception as e:
                print("Error initializing drs")
                print("Exception: " + (str(e)))
                responseData = {}
                print("Sending Failed CFN Response to CloudFormation")
                cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
                raise e
            else:
              print(f'Processing a {request_type} request')
              print("Removing DRS replication config")
              rId = event['PhysicalResourceId']
              if "rct-" in rId:
                response = drs.delete_replication_configuration_template(replicationConfigurationTemplateID=rId)

            print("Sending Success CFN Response to CloudFormation")
            responseData = {}
            responseData['Data'] = response
            cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, rId)

  rDrsInitializer:
    Type: Custom::DRSInitializer
    Properties:
      ServiceToken: !GetAtt rDRSInitializerLambdaFunction.Arn
      CreateReplicationSecurityGroup: !Ref pCreateReplicationSecurityGroup
      CreatePublicIp: !Ref pReplicationServerPublicIp
      KMSKeyArn: !Ref pKMSKeyArn
      ReplicationInstanceType: !Ref pReplicationInstanceType
      ReplicationSecurityGroupIds: !Ref pReplicationSecurityGroupIds
      ReplicationDataRouting: !Ref pReplicationServerDataRouting
      StagingSubnetId: !Ref pReplicationSubnetId
      ReplicationBandwidthInMB: !Ref pReplicationDataThrottling
      StagingDiskType: !Ref pReplicationStagingDiskType
      Tags: !Ref pReplicationServerTags
      UseDedicatedReplicationServer: !Ref pUseDedicatedReplicationServer
      PitPolicyMinute: !Ref pPitPolicyMinute
      PitPolicyHour: !Ref pPitPolicyHour
      PitPolicyDay: !Ref pPitPolicyDay

Outputs:
  oReplicationConfigurationTemplateId:
    Description: Replication Configuration template ID
    Value: !Ref rDrsInitializer
